services:
  ubuntu:
    # user: $UID:$GID
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # UID: $UID
        # GID: $GID
        USERNAME: $USERNAME
    tty: true
    develop:
      watch:
        - action: sync
          path: ./dotfiles
          target: /home/y_ohi/dotfiles
          ignore:
            - .git
    # volumes:
    #   # - .dots/:/home/yohi/dotfiles
    #   - ./dotfiles/:/home/yohi/dotfiles:cached
